In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# loading data 
data = pd.read_csv("C:\\Users\\nthambat\\Downloads\\Fraud_check.csv")
data.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [4]:
data.loc[data['Taxable.Income'] <=30000,'Taxable_Income']= 'Risky'
data.loc[data['Taxable.Income'] >30000,'Taxable_Income']= 'Good'

In [5]:
data.head(2)

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   

  Urban Taxable_Income  
0   YES           Good  
1   YES           Good

In [6]:
data.drop('Taxable.Income',1,inplace=True)

In [7]:
data['Marital.Status'].value_counts()

Single      217
Married     194
Divorced    189
Name: Marital.Status, dtype: int64

In [8]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
data['Marital.Status']= label_encoder.fit_transform(data['Marital.Status']) 
data['Marital.Status'].unique() 

array([2, 0, 1], dtype=int64)

In [9]:
data.head(2)

Undergrad  Marital.Status  City.Population  Work.Experience Urban  \
0        NO               2            50047               10   YES   
1       YES               0           134075               18   YES   

  Taxable_Income  
0           Good  
1           Good

In [10]:
data.Undergrad.value_counts()

YES    312
NO     288
Name: Undergrad, dtype: int64

In [11]:
data['Undergrad']= label_encoder.fit_transform(data['Undergrad']) 
data['Undergrad'].unique() 

array([0, 1], dtype=int64)

In [12]:
data.Urban.value_counts()

YES    302
NO     298
Name: Urban, dtype: int64

In [13]:
data['Urban']= label_encoder.fit_transform(data['Urban']) 
data['Urban'].unique() 

array([1, 0], dtype=int64)

In [14]:
data.head()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
0          0               2            50047               10      1   
1          1               0           134075               18      1   
2          0               1           160205               30      1   
3          1               2           193264               15      1   
4          0               1            27533               28      0   

  Taxable_Income  
0           Good  
1           Good  
2           Good  
3           Good  
4           Good

In [15]:
colnames = list(data.columns)
predictors = colnames[0:5]
target = colnames[5]

In [16]:
predictors

['Undergrad', 'Marital.Status', 'City.Population', 'Work.Experience', 'Urban']

In [17]:
target

'Taxable_Income'

In [18]:
X = data[predictors]
Y = data[target]

In [19]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion="entropy")
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [20]:
data['rf_pred'] = rf.predict(X)

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(data['sales'],data['rf_pred'])

KeyError: 'sales'