# Numpy

In [1]:
import numpy as np

In [3]:
a= np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
a=np.array([[1,2,3,4,5],[4,6,7,8]])
print(a)

[list([1, 2, 3, 4, 5]) list([4, 6, 7, 8])]


In [13]:
a[0][:3]

[1, 2, 3]

In [14]:
a[:,:2]

IndexError: too many indices for array

# Types

In [18]:
b=np.zeros((2,6))
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
b=np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
b=np.full((2,3),56)
b

array([[56, 56, 56],
       [56, 56, 56]])

In [23]:
b*2

array([[112, 112, 112],
       [112, 112, 112]])

In [25]:
b=np.identity(6)
b

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
a = np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
a[2][2] =100

In [33]:
a

array([[  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0.]])

# Random

In [35]:
a=np.random.rand(2,3)
a

array([[0.44903373, 0.6327945 , 0.82607906],
       [0.19997922, 0.41629024, 0.31911814]])

In [40]:
#under 2 values randomly will display
b=np.random.randint(2)
b

1

In [42]:
#between 10 to 100 random values will dislay
b=np.random.randint(10,100)
b

54

In [45]:
#4 values between 10 to 15 randomly
b = np.random.randint(10,15,4)
b

array([12, 14, 12, 12])

In [46]:
a= b 
# if u change b automatically a will change.so will use copy function
a=b.copy()
#reference will copy

# min max and shape

In [47]:
a=np.array([[1,2,3,4],[1,9,8,7]])

In [48]:
a.min()

1

In [49]:
a.max()

9

In [50]:
#wont work
min(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [53]:
a.shape

(2, 4)

In [54]:
a.ndim


2

In [60]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [1, 9],
       [8, 7]])

# linspace

In [62]:
a=np.linspace(1,10)
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [64]:
#2 values between 1 to 6
a=np.linspace(1,6,2)
a

array([1., 6.])

# comparision

In [65]:
a

array([1., 6.])

In [66]:
a>2

array([False,  True])

# stacks

In [70]:
#vstack - vertical stack
#hstack -- horizantal stack

In [69]:
b=np.vstack(a)
b

array([[1.],
       [6.]])

In [71]:
b.ndim

2

In [72]:
b=np.vstack(b)
b

array([[1.],
       [6.]])

In [73]:
b.ndim

2